name: Build Workflow

on:
  push:
    branches: main

permissions:
  contents: write
  pull-requests: read

jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
      tag_name: ${{ steps.create-release.outputs.tag_name }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release Tag
        uses: DasBen/release-on-push-action@master
        id: create-release
        with:
          bump_version_scheme: minor
          tag_prefix: v

      - name: Check Output Parameters
        run: |
          echo "Upload release artifacts to ${{ steps.create-release.outputs.upload_url }}"
          echo "Got tag name ${{ steps.create-release.outputs.tag_name }}"
          echo "Got release version ${{ steps.create-release.outputs.version }}"

  build-windows:
    if: ${{ needs.main.outputs.upload_url != '' }}
    runs-on: windows-latest
    needs: main
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.7'
          architecture: 'x64'
          cache: 'pip'

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run PyInstaller and zip
        shell: pwsh
        run: |
          python -m PyInstaller main.spec
          Compress-Archive -Path dist/main/* -DestinationPath tarkov_item_analyzer_windows.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: tarkov_item_analyzer_windows_${{ needs.main.outputs.tag_name }}.zip
          path: tarkov_item_analyzer_windows.zip

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.main.outputs.upload_url }}
          asset_path: tarkov_item_analyzer_windows.zip
          asset_name: tarkov_item_analyzer_windows_${{ needs.main.outputs.tag_name }}.zip
          asset_content_type: application/zip

  build-mac:
    if: ${{ needs.main.outputs.upload_url != '' }}
    runs-on: macos-latest
    needs: main
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.7'
          architecture: 'x64'
          cache: 'pip'

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run PyInstaller and zip
        run: |
          python -m PyInstaller main.spec
          zip -vr tarkov_item_analyzer_mac.zip dist/main

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: tarkov_item_analyzer_mac_${{ needs.main.outputs.tag_name }}.zip
          path: tarkov_item_analyzer_mac.zip

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.main.outputs.upload_url }}
          asset_path: tarkov_item_analyzer_mac.zip
          asset_name: tarkov_item_analyzer_mac_${{ needs.main.outputs.tag_name }}.zip
          asset_content_type: application/zip
